name: cocoroiki_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  audioplayers: ^4.0.1
  http: '>=0.13.0 <0.14.0'
  intl: ^0.18.1
  meta: '^1.1.8'
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  lottie: ^2.3.2
  image_picker: ^0.8.9
  stroke_text: ^0.0.2
  json_annotation: ^4.0.1
  
  #flutter_reaction_button: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.6 
  json_serializable: ^4.1.3

flutter:

  uses-material-design: true

  fonts:
   - family: Zen-M
     fonts:
        - asset: assets/font/ZenKakuGothicNew-Medium.ttf

   - family: Zen-B
     fonts:
        - asset: assets/font/ZenKakuGothicNew-Bold.ttf  



  assets:
    - assets/svg/
    - assets/image/
    - assets/json/
  

  

